### ISSUE TITLE
'float' object cannot be interpreted as an integer??

### ISSUE THREAD

**Issue by door5719** [clcarwin/SFD_pytorch#17]
Sir,I'm sorry to disturb  you about this object.
I run this object on windows 10,python 3.5.2 ,pytorch 0.3.
After : python test.py --model data/s3fd_convert.pth --path data/test01.jpg,
the screen display:
D:\Python\Pytorch_cw_sfd\SFD_pytorch>python test.py --model data/s3fd_convert.pth --path data/test01.jpg
Traceback (most recent call last):
  File "test.py", line 71, in <module>
    bboxlist = detect(net,img)
  File "test.py", line 27, in detect
    for i in range(len(olist)/2): olist[i*2] = F.softmax(olist[i*2])
TypeError: 'float' object cannot be interpreted as an integer

Why ???

**Comment by BCJuan** [comment]
Hi, 

I know this issue is quite old, but I have encountered the same error after fresh cloning the project.

How did you solved it? Changing `/` by `//`?

Thanks
