### ISSUE TITLE
padding size of fc6

### ISSUE THREAD

**Issue by marvis** [clcarwin/SFD_pytorch#2]
Hi @clcarwin,

Why do you set the padding size of fc6 to 3? This is inconsistent with the original paper.
See https://github.com/clcarwin/SFD_pytorch/blob/master/net_s3fd.py#L42

Best,

**Comment by foralliance** [comment]
@marvis @clcarwin 
have u solved the problem??

from [this issue](https://github.com/sfzhang15/SFD/issues/9), i think the pad should equal **1**
