### ISSUE TITLE
evaluation accuracy is not good as the original paper

### ISSUE THREAD

**Issue by marvis** [clcarwin/SFD_pytorch#3]
hi @clcarwin,

I test you evaluation results on wider face as (easy 92.8, medium 91.5, hard 84.2). But with the original model provided by sfzhang15/SFD,  I can get (easy 93.8, medium 92.4, hard 85.1). 

Did I test correctly? If so, why there is accuracy loss?

Great work! 
Best,

**Comment by clcarwin** [comment]
Yes, the result is correct. It may be caused by different algorithms or different eps in caffe and pytorch.

**Comment by kohenchia** [comment]
This won't lead to a 1% accuracy difference, but the normalization layer in the Caffe version applies the square root after adding `eps`: https://github.com/weiliu89/caffe/blob/ssd/src/caffe/layers/normalize_layer.cu#L76
```
norm_data[n] = pow(normsqr+eps_, Dtype(0.5));
```

Whereas this PyTorch version does the reverse (applies square root before adding `eps`):
https://github.com/clcarwin/SFD_pytorch/blob/master/net_s3fd.py#L17
```
norm = x.pow(2).sum(dim=1, keepdim=True).sqrt()+self.eps
```
