### ISSUE TITLE
RGB <-> BGR

### ISSUE THREAD

**Issue by elbaro** [clcarwin/SFD_pytorch#6]
From this line, I assume you use RGB:
```img = img - np.array([104,117,123])```

However opencv uses BGR, so this line returns BGR:
```if args.path=='CAMERA': ret, img = cap.read()```

Then BGR is fed to the network
```bboxlist = detect(net,img)```

I fed RGB to the network and got worse results.
Is it possible that you meant RGB in all places but the network is actually trained for BGR?
(If then it should be `img = img - np.array([123,117,104])`)

**Comment by pkdogcom** [comment]
I have the same concern. Let me know if you've found which color space it actually uses.

**Comment by clcarwin** [comment]
The model is converted from caffe, BGR is used.

**Comment by elbaro** [comment]
Everything seems correct.
https://groups.google.com/forum/#!topic/lasagne-users/cCFVeT5rw-o
