### ISSUE TITLE
How Convert Weights

### ISSUE THREAD

**Issue by ahkarami** [clcarwin/SFD_pytorch#9]
Dear @clcarwin,
Thank you for your nice work. Would you please tell me how you can convert Caffe weights and model of S3FD into PyTorch?
Can you convert the model & pre-trained weights of [_RefineDet_](https://github.com/sfzhang15/RefineDet) into PyTorch?

**Comment by clcarwin** [comment]
1. Convert caffemodel to numpy array [caffemodel2json_to_npy](https://github.com/clcarwin/caffemodel2json_to_npy).
2. Copy numpy array to Pytorch weight.

**Comment by ahkarami** [comment]
Thank you.
